In [1]:
import pandas as pd

df = pd.read_csv("bicicletas_compartidas_bogota.csv")

In [2]:

df.head()

,viaje_id,inicio_viaje,estacion_origen,localidad_origen,estacion_destino,localidad_destino,duracion_min,distancia_km,tipo_bicicleta,tipo_usuario,clima,temperatura_c,precipitacion_mm,fin_de_semana
0,V000671,2026-04-22 08:35:33,Plaza de Bolívar,La Candelaria,Universidades Centro,La Candelaria,13.8,4.14,Eléctrica,Suscriptor,Nublado,17.2,0.0,No
1,V002336,2026-03-26 20:39:41,Plaza de Bolívar,La Candelaria,Universidades Centro,La Candelaria,10.8,2.47,Eléctrica,Ocasional,Lluvia ligera,15.2,0.9,No
2,V002504,2026-03-09 11:25:42,Parque de los Novios,Barrios Unidos,Hacienda Santa Bárbara,Usaquén,6.6,0.83,Eléctrica,Suscriptor,Nublado,17.1,0.0,No
3,V002587,2026-04-29 04:04:46,Parque de la 93,Chapinero,Parque de la 93,Chapinero,7.6,1.68,Mecánica,Suscriptor,Nublado,21.0,0.0,No
4,V000820,2026-05-26 03:55:26,Zona G,Chapinero,Parque Nacional,Santa Fe,16.6,2.89,Mecánica,Suscriptor,Lluvia,18.7,7.8,No

In [3]:
df.shape

(3214, 14)

In [4]:
df.columns

Index(['viaje_id', 'inicio_viaje', 'estacion_origen', 'localidad_origen',
       'estacion_destino', 'localidad_destino', 'duracion_min', 'distancia_km',
       'tipo_bicicleta', 'tipo_usuario', 'clima', 'temperatura_c',
       'precipitacion_mm', 'fin_de_semana'],
      dtype='str')

In [5]:
df.describe()

       duracion_min  distancia_km  temperatura_c  precipitacion_mm
count   3214.000000   3162.000000    3169.000000       3214.000000
mean      14.231518      2.853033      16.647144          0.996235
std        8.670122      1.698718       2.356015          2.459092
min        0.500000      0.050000       8.000000          0.000000
25%        8.900000      1.710000      15.100000          0.000000
50%       12.500000      2.480000      16.600000          0.000000
75%       17.600000      3.580000      18.300000          0.150000
max      180.000000     31.200000      24.900000         12.000000

In [6]:
df.dtypes

viaje_id                 str
inicio_viaje             str
estacion_origen          str
localidad_origen         str
estacion_destino         str
localidad_destino        str
duracion_min         float64
distancia_km         float64
tipo_bicicleta           str
tipo_usuario             str
clima                    str
temperatura_c        float64
precipitacion_mm     float64
fin_de_semana            str
dtype: object

In [8]:
df[["distancia_km","duracion_min"]].corr()

              distancia_km  duracion_min
distancia_km      1.000000      0.721721
duracion_min      0.721721      1.000000